-- ========================================================
-- İŞ MAKİNESİ TAKİP & CARİ HESAP SİSTEMİ - SUPABASE TABLO KURULUMU
-- Bu SQL kodlarını Supabase paneline girip SQL Editor kısmına yapıştırın ve "RUN" butonuna basın.
-- ========================================================

-- 1. FİRMALAR TABLOSU
CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. MAKİNELER TABLOSU
CREATE TABLE IF NOT EXISTS public.machines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. OPERATÖRLER TABLOSU
CREATE TABLE IF NOT EXISTS public.operators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ÇALIŞMA (MESAİ) KAYITLARI TABLOSU
CREATE TABLE IF NOT EXISTS public.work_records (
    id BIGINT PRIMARY KEY,
    company_name TEXT NOT NULL,
    machine_name TEXT NOT NULL,
    operator TEXT NOT NULL,
    hourly_rate NUMERIC(12, 2) NOT NULL DEFAULT 0,
    start_time_iso TEXT NOT NULL,
    end_time_iso TEXT NOT NULL,
    formatted_start TEXT,
    formatted_end TEXT,
    duration_hours NUMERIC(10, 2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TAHSİLAT / ÖDEME KAYITLARI TABLOSU
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT PRIMARY KEY,
    company_name TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    payment_date TEXT NOT NULL,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ROW LEVEL SECURITY (RLS) POLİTİKALARI
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.machines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.operators ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anon Access Companies" ON public.companies;
DROP POLICY IF EXISTS "Anon Access Machines" ON public.machines;
DROP POLICY IF EXISTS "Anon Access Operators" ON public.operators;
DROP POLICY IF EXISTS "Anon Access Work Records" ON public.work_records;
DROP POLICY IF EXISTS "Anon Access Payments" ON public.payments;

CREATE POLICY "Anon Access Companies" ON public.companies FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Anon Access Machines" ON public.machines FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Anon Access Operators" ON public.operators FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Anon Access Work Records" ON public.work_records FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Anon Access Payments" ON public.payments FOR ALL USING (true) WITH CHECK (true);

-- VARSAYILAN BAŞLANGIÇ VERİLERİ
INSERT INTO public.companies (name) VALUES ('ABC İnşaat A.Ş.'), ('Örnek Hafriyat') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.machines (name) VALUES ('MAVİ MANİTU'), ('Ekskavatör'), ('Loder'), ('JCB') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.operators (name) VALUES ('MUSTAFA ÖZYILMAZ'), ('Ahmet Yılmaz'), ('Mehmet Demir') ON CONFLICT (name) DO NOTHING;
