-- ========================================================
-- İŞ MAKİNESİ TAKİP & CARİ HESAP SİSTEMİ - SUPABASE TABLO KURULUMU
-- Bu SQL kodlarını Supabase paneline girip SQL Editor kısmına yapıştırın ve "RUN" butonuna basın.
-- ========================================================

-- 1. FİRMALAR TABLOSU
CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    invoice_title TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Firma tablosuna resmi fatura başlığı sütunu ekleme
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS invoice_title TEXT DEFAULT '';

-- 2. MAKİNELER TABLOSU
CREATE TABLE IF NOT EXISTS public.machines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    default_rate NUMERIC(12, 2) DEFAULT 0,
    default_operator TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Makine tablosuna varsayılan saat ücreti ve operatör sütunlarını ekleme
ALTER TABLE public.machines ADD COLUMN IF NOT EXISTS default_rate NUMERIC(12, 2) DEFAULT 0;
ALTER TABLE public.machines ADD COLUMN IF NOT EXISTS default_operator TEXT DEFAULT '';

-- 3. OPERATÖRLER TABLOSU
CREATE TABLE IF NOT EXISTS public.operators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ÇALIŞMA (MESAİ) KAYITLARI TABLOSU
CREATE TABLE IF NOT EXISTS public.work_records (
    id BIGINT PRIMARY KEY,
    company_name TEXT NOT NULL,
    machine_name TEXT NOT NULL,
    operator TEXT NOT NULL,
    hourly_rate NUMERIC(12, 2) NOT NULL DEFAULT 0,
    start_time_iso TEXT NOT NULL,
    end_time_iso TEXT NOT NULL,
    formatted_start TEXT,
    formatted_end TEXT,
    duration_hours NUMERIC(10, 2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    extra_note TEXT DEFAULT '',
    invoice_no TEXT DEFAULT '',
    invoice_date TEXT DEFAULT '',
    invoice_issued BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ek Not ve Fatura sütunlarının mevcut tablolarda varlığından emin olma
ALTER TABLE public.work_records ADD COLUMN IF NOT EXISTS extra_note TEXT DEFAULT '';
ALTER TABLE public.work_records ADD COLUMN IF NOT EXISTS invoice_no TEXT DEFAULT '';
ALTER TABLE public.work_records ADD COLUMN IF NOT EXISTS invoice_date TEXT DEFAULT '';
ALTER TABLE public.work_records ADD COLUMN IF NOT EXISTS invoice_issued BOOLEAN DEFAULT FALSE;

-- 5. TAHSİLAT / ÖDEME KAYITLARI TABLOSU
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT PRIMARY KEY,
    company_name TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    payment_date TEXT NOT NULL,
    note TEXT,
    invoice_no TEXT DEFAULT '',
    invoice_date TEXT DEFAULT '',
    invoice_issued BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tahsilat tablosuna fatura sütunlarını ekleme
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS invoice_no TEXT DEFAULT '';
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS invoice_date TEXT DEFAULT '';
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS invoice_issued BOOLEAN DEFAULT FALSE;

-- 6. SİSTEM AYARLARI VE ŞİFRE KARMASI TABLOSU
CREATE TABLE IF NOT EXISTS public.app_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ROW LEVEL SECURITY (RLS) POLİTİKALARI
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.machines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.operators ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anon Access Companies" ON public.companies;
DROP POLICY IF EXISTS "Anon Access Machines" ON public.machines;
DROP POLICY IF EXISTS "Anon Access Operators" ON public.operators;
DROP POLICY IF EXISTS "Anon Access Work Records" ON public.work_records;
DROP POLICY IF EXISTS "Anon Access Payments" ON public.payments;
DROP POLICY IF EXISTS "Anon Access App Settings" ON public.app_settings;

CREATE POLICY "Anon Access Companies" ON public.companies FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Anon Access Machines" ON public.machines FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Anon Access Operators" ON public.operators FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Anon Access Work Records" ON public.work_records FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Anon Access Payments" ON public.payments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Anon Access App Settings" ON public.app_settings FOR ALL USING (true) WITH CHECK (true);

-- VARSAYILAN BAŞLANGIÇ VERİLERİ
INSERT INTO public.companies (name) VALUES ('ABC İnşaat A.Ş.'), ('Örnek Hafriyat') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.machines (name) VALUES ('MAVİ MANİTU'), ('Ekskavatör'), ('Loder'), ('JCB') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.operators (name) VALUES ('MUSTAFA ÖZYILMAZ'), ('Ahmet Yılmaz'), ('Mehmet Demir') ON CONFLICT (name) DO NOTHING;
